### PR TITLE
added anchor tag for the file type of attribute

### PR DESCRIPTION
**Pull request by erankitsrivastava**
added anchor tag for the file type of attribute

### CODE REVIEW

**Comment by erankitsrivastava** [comment]
I have changed the select type product attribute to multi-select in add product form,
and managed it on frontend,

**Comment by tangar76** [comment]
Thanks for contribution.

**Comment by tangar76** [comment]
We appreciate your contribution . There is small issue in admin after saving tab. Multiselect with product attributes is not set with selected attributes. Can you please fix it?

Screenshot - https://prnt.sc/pcxv3r

For tab I select attributes product name, SKU and price.

**Comment by tangar76** [comment]
This is my first time with pull requests. And I messed up a little bit.
I have added most of your changes to repo master. Except template changes. And fixed issue with multiselect.

**Pull request closed without merging**
